# Generated by Django 5.2.9 on 2025-12-27 12:42

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(default=api.models.create_user_company, on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
    ]
