# Generated by Django 5.2.9 on 2026-01-01 00:30

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(default=api.models.create_user_company, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.company'),
        ),
    ]
